services:
  geonerd:
    build:
      context: .
    container_name: geonerd-app
    ports:
      - "8000:80"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
    restart: unless-stopped

  db:
    image: mysql:8
    container_name: geonerd-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - geonerd-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  geonerd-db-data: