services:
  server:
    build:
      context: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html:cached
    depends_on:
      - db
    env_file:
      - .env.local
    command: >
      bash -c "chown -R www-data:www-data var && apache2-foreground"

  db:
    image: mysql:8
    restart: always
    env_file:
      - .env.local
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
