version: "3.8"

services:
  geonerd:
    build:
      context: .
    container_name: geonerd-app
    ports:
      - "8000:80"
    depends_on:
      - db
    env_file:
      - .env.prod
    command: >
      bash -c "chown -R www-data:www-data var && apache2-foreground"
    restart: unless-stopped

  db:
    image: mysql:8
    container_name: geonerd-db
    restart: unless-stopped
    env_file:
      - .env.prod
    volumes:
      - geonerd-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

volumes:
  geonerd-db-data:
